RS       EQU P3.7 ;Pin  4    - 1 is for DATA, 0 is for COMMANDS - (RS)
RD_WR    EQU P3.6 ;Pin  5    - 0 is for WRITE
ENABLE   EQU P3.5 ;Pin  6    - SETB to SEND ?*
LCD_PORT EQU P1   ;Pins 7-14 - MSB at 14
CS_1     EQU P3.4 ;Pin  15   - 0 = selected ?*
CS_2     EQU P3.3 ;Pin  16   - 0 = selected ?*

ORG 0000H
 MAIN:
 ACALL CONFIGURE_LCD
 MOV A, #01H
 ACALL SEND_BYTE
 MOV A, #03H
 ACALL SEND_BYTE
 MOV A, #07H
 ACALL SEND_BYTE
 MOV A, #0FH
 ACALL SEND_BYTE
 MOV A, #0FFH
 ACALL SEND_BYTE

 CLR  CS_2
 SETB CS_1
 
 MOV A, #0FFH
 ACALL SEND_BYTE
 MOV A, #81H
 ACALL SEND_BYTE
 ACALL SEND_BYTE
 ACALL SEND_BYTE
 ACALL SEND_BYTE
 MOV A, #0FFH
 ACALL SEND_BYTE

 SJMP $

 CONFIGURE_LCD:
   ;;DELAY 32ms
 MOV TMOD,#01H
 MOV TH0, #HIGH (33536)
 MOV TL0, #LOW  (33536)
 CLR TF0
 SETB TR0
 JNB TF0, $
 CLR TR0

   ;;Clear Both Chips
 CLR  CS_1
 CLR  CS_2

 MOV  LCD_PORT, #11000000b; Set disp line to first line
 CLR  RD_WR;
 CLR  RS
 SETB ENABLE
 NOP
 NOP
 CLR  ENABLE
 
 MOV  LCD_PORT, #00111111b; Set disp ON
 SETB ENABLE
 NOP
 NOP
 CLR  ENABLE
 
   ;;Select Chip 1
 CLR  CS_1
 SETB CS_2

 RET

 SEND_CMD:
 MOV  LCD_PORT, A
 CLR  RD_WR;
 CLR  RS
 SETB ENABLE
 NOP
 NOP
 CLR  ENABLE
 RET

 SEND_BYTE:
 MOV  LCD_PORT, A
 CLR  RD_WR;
 SETB RS
 SETB ENABLE
 NOP
 NOP
 CLR  ENABLE
 RET
